import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :todo_app, TodoAppWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# ========================================================= #

config :todo_app, TodoApp.Repo, pool_size: String.to_integer(System.get_env("POOL_SIZE") || "5")

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

# host = System.get_env("PHX_HOST") || "example.com"
# port = String.to_integer(System.get_env("PORT") || "4000")

config :todo_app, :dns_cluster_query, System.get_env("DNS_CLUSTER_QUERY")

config :todo_app, TodoAppWeb.Endpoint,
  # url: [host: host, port: 443, scheme: "https"],
  # http: [
  #   # Enable IPv6 and bind on all interfaces.
  #   # Set it to  {0, 0, 0, 0, 0, 0, 0, 1} for local network only access.
  #   # See the documentation on https://hexdocs.pm/bandit/Bandit.html#t:options/0
  #   # for details about using IPv6 vs IPv4 and loopback vs public addresses.
  #   ip: {0, 0, 0, 0, 0, 0, 0, 0},
  #   port: port
  # ],
  # Step 1: set the port number to 0, so the port can be chosen automatically.
  http: [ip: {127, 0, 0, 1}, port: 0],
  # Step 2: start endpoint automatically, so we have no need to start it manually.
  server: true,
  secret_key_base: secret_key_base

# ========================================================================== #

# export WEBKIT_DISABLE_COMPOSITING_MODE=1

# mix phx.gen.secret ==>
# export SECRET_KEY_BASE=crvAke0S0ca5IePbc8W88EIwhElKGSqrD2bVFrDMYda42Fn3dMe5stz1O1JbnuAX
