name: "Build binaries"

on:
  push:
    branches:
      - deployment
      
env:
  OTP_GITHUB_URL: https://github.com/diodechain/otp.git
  OTP_VERSION: OTP-26.2.5.9_diode
  WXWIDGETS_REPO: https://github.com/wxWidgets/wxWidgets.git
  WXWIDGETS_VERSION: v3.2.6
  ELIXIR_VERSION: 1.16.3
  ELIXIR_VARIANT: -otp-26
  DOCKER_BUILDKIT: 0

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: wsl-bash {0}
    name: Build Erlang/OTP (Windows)
    steps:
    - name: Restore Windows Cache
      uses: actions/cache/restore@v3
      id: win32-cache
      with:
        path: "c:\\opt\\otp.exe"
        key: win32-wxwidgets-${{ env.WXWIDGETS_VERSION }}-otp-${{ env.OTP_VERSION }}
  
    - uses: Vampire/setup-wsl@v2
      if: steps.win32-cache.outputs.cache-hit != 'true'
      with:
        distribution: Ubuntu-18.04

    - name: Install WSL dependencies
      if: steps.win32-cache.outputs.cache-hit != 'true'
      run: apt update && apt install -y g++-mingw-w64 gcc-mingw-w64 make autoconf unzip

    - name: Install openssl
      if: steps.win32-cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        choco install openssl --version=1.1.1.2100
        IF EXIST "c:\\Program Files\\OpenSSL-Win64" (move "c:\\Program Files\\OpenSSL-Win64" "c:\\OpenSSL-Win64") ELSE (move "c:\\Program Files\\OpenSSL" "c:\\OpenSSL-Win64")
 
    - name: Download wxWidgets
      if: steps.win32-cache.outputs.cache-hit != 'true'
      run: |
        git clone ${{ env.WXWIDGETS_REPO }}
        cd wxWidgets
        git checkout ${{ env.WXWIDGETS_VERSION }}
        git submodule update --init
        sed -i -r -e 's/wxUSE_POSTSCRIPT +0/wxUSE_POSTSCRIPT 1/' include/wx/msw/setup.h
        sed -i -r -e 's/wxUSE_WEBVIEW_EDGE +0/wxUSE_WEBVIEW_EDGE 1/' include/wx/msw/setup.h        
        sed -i -r -e 's/WXWIN_COMPATIBILITY_3_0 +0/WXWIN_COMPATIBILITY_3_0 1/' include/wx/msw/setup.h        

    - name: Install WebView2
      if: steps.win32-cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        cd wxWidgets\\3rdparty
        nuget install Microsoft.Web.WebView2 -Version 1.0.864.35 -Source https://api.nuget.org/v3/index.json
        rename Microsoft.Web.WebView2.1.0.864.35 webview2

    - name: Build wxWidgets
      if: steps.win32-cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        cd wxWidgets\\build\\msw
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\Auxiliary\\Build\\vcvars64.bat"
        nmake TARGET_CPU=amd64 BUILD=release SHARED=0 DIR_SUFFIX_CPU= -f makefile.vc

    - name: Copy wxWidgets
      if: steps.win32-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /mnt/c/opt/local64/pgm/
        cp -R wxWidgets /mnt/c/opt/local64/pgm/wxWidgets-3.x.x

    - name: Compile Erlang
      if: steps.win32-cache.outputs.cache-hit != 'true'
      run: |
        git clone ${{ env.OTP_GITHUB_URL }}
        cd otp
        git checkout ${{ env.OTP_VERSION }}
        export ERL_TOP=`pwd`
        export MAKEFLAGS=-j$(($(nproc) + 2))
        export ERLC_USE_SERVER=true
        export ERTS_SKIP_DEPEND=true
        eval `./otp_build env_win32 x64`
        ./otp_build all -a 
        cp /mnt/c/opt/local64/pgm/wxWidgets-3.x.x/3rdparty/webview2/runtimes/win-x64/native/WebView2Loader.dll $ERL_TOP/release/win32/erts-*/bin/
        ./otp_build installer_win32
        export NAME=`ls release/win32/otp*.exe`
        cp $NAME /mnt/c/opt/otp.exe

    - name: Save Windows Cache
      if: steps.win32-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: "c:\\opt\\otp.exe"
        key: win32-wxwidgets-${{ env.WXWIDGETS_VERSION }}-otp-${{ env.OTP_VERSION }}
  
    - name: Run Erlang installer
      shell: cmd
      run: C:\\opt\\otp.exe /S

    - name: "Install msys2"
      uses: msys2/setup-msys2@v2
      with:
          install: pacman-mirrors pkg-config base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-go upx mingw-w64-x86_64-dlfcn unzip git tar mingw-w64-x86_64-nodejs mingw-w64-x86_64-imagemagick mingw-w64-x86_64-osslsigncode autoconf automake libtool gettext-devel gettext
          update: true

    - name: Locate Erlang
      shell: msys2 {0}
      run: |
        ERTS=`find /c/Program\ Files/[Ee]rl* -type d -name "erts-*" -not -path "*lib*"`
        echo $ERTS
        echo export PATH=\"\$PATH:$ERTS/bin\" > $HOME/.bashrc

    - name: Locate NSIS
      shell: msys2 {0}
      run: |
        echo export PATH=\"\$PATH:/c/Program\ Files\ \(x86\)/NSIS\" >> $HOME/.bashrc
    
    - name: Install Elixir
      shell: msys2 {0}
      run: |
        cd $HOME
        git clone https://github.com/elixir-lang/elixir.git
        cd elixir
        git checkout v${{ env.ELIXIR_VERSION }}
        make 
        echo export PATH=\"\$PATH:$HOME/elixir/bin\" >> $HOME/.bashrc
    
    - uses: actions/checkout@v1

    - name: "Get dependencies"
      shell: msys2 {0}
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: "npm install"
      shell: msys2 {0}
      run: |
        cd assets && npm install

    - name: "Build Release"
      env:
        MAKE: make
        REBAR_TARGET_ARCH_WORDSIZE: 64 
        REBAR_TARGET_ARCH: x86_64-w64-mingw32
        WIN32_KEY_PASS: ${{ secrets.WIN32_KEY_PASS }}
      shell: msys2 {0}
      run: |
        mix assets.deploy
        mix desktop.installer

    - name: Archive Installer
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: |
          _build/prod/*.exe